#!/bin/sh

### BEGIN INIT INFO
# Provides:  plone
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:    1
# Short-Description: Start Plone
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

NAME=plone
BINDIR=/srv/plone/zeocluster/bin
SUPERVISORCTL=$BINDIR/supervisorctl
SUPERVISORD=$BINDIR/supervisord

case $1 in
  start)
    log_daemon_msg "Starting Plone" "supervisord"
    $SUPERVISORD
    ;;
  stop)
    log_daemon_msg "Stopping Plone" "supervisord"
    $SUPERVISORCTL shutdown
    ;;
  restart|force-reload)
    $SUPERVISORCTL restart all
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|force-reload}"
    exit 2
    ;;
esac
